{
  "openapi": "3.0.3",
  "info": {
    "version": "1.0.0",
    "title": "Swagger GooseTrack",
    "description": "This project is a web application for managing personal affairs.",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json, multipart/form-data"],
  "produces": ["application/json"],
  "servers": [
    { "url": "https://goose-calendar.onrender.com/" },
    { "url": "http://localhost:3001" }
  ],
  "tags": [
    {
      "name": "Users",
      "description": "Users endpoints"
    },
    {
      "name": "Reviews",
      "description": "Reviews endpoints"
    },
    {
      "name": "Tasks",
      "description": "Tasks endpoints"
    }
  ],
  "paths": {
    "/users/register": {
      "post": {
        "tags": ["Users"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request(invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Email already in use",
            "content": {}
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "tags": ["Users"],
        "summary": "Login user",
        "parameters": [],
        "requestBody": {
          "description": "Login object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User is logged in",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "401": {
            "description": "Email or password is wrong",
            "content": {}
          }
        }
      }
    },
    "/users/logout": {
      "post": {
        "tags": ["Users"],
        "summary": "Log out user",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": {
            "description": "Logout is successed"
          },
          "401": {
            "description": "Not authorized"
          }
        }
      }
    },
    "/users/current": {
      "get": {
        "tags": ["Users"],
        "summary": "Get information about the current user",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Information found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentUserResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          }
        }
      }
    },
    "/users/update": {
      "patch": {
        "tags": ["Users"],
        "summary": "Update user's information",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Update object",
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateUserResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          }
        }
      }
    },
    "/users/refresh": {
      "post": {
        "tags": ["Users"],
        "summary": "Get new user's tokens",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Refresh object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RefreshTokenRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RefreshTokenResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          },
          "403": {
            "description": "Token is invalid"
          }
        }
      }
    },

    "/reviews": {
      "get": {
        "tags": ["Reviews"],
        "summary": "Get all reviews",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Reviews collection found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReviewsResponse"
                }
              }
            }
          },
          "500": {
            "description": "Server error"
          }
        }
      },
      "post": {
        "tags": ["Reviews"],
        "summary": "Create a new review",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Review's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ReviewCreationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "ОК - Review was successfully created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReviewCreationResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          },
          "404": {
            "description": "Bad request(invalid request body)"
          },
          "409": {
            "description": "User already has a review"
          }
        }
      }
    },
    "/reviews/{id}": {
      "get": {
        "tags": ["Reviews"],
        "summary": "Get review by user's id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "example": "64983b139dd09fca9aaa6da4"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "ОК",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReviewByUserIdResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          },
          "404": {
            "description": "Not found"
          }
        }
      },
      "delete": {
        "tags": ["Reviews"],
        "summary": "Delete review by user's id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "user's id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": {
            "description": "ОК-Review deleted"
          },
          "401": {
            "description": "Not authorized"
          },
          "404": {
            "description": "Not found"
          }
        }
      },
      "patch": {
        "tags": ["Reviews"],
        "summary": "Update review by user's id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "user's id",
            "example": "64983b139dd09fca9aaa6da4"
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Review's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ReviewUpdateRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "ОК",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReviewUpdateResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          },
          "404": {
            "description": "Bad request(invalid request body)"
          }
        }
      }
    },

    "/tasks": {
      "get": {
        "tags": ["Tasks"],
        "summary": "Get user's tasks for month",
        "parameters": [
          {
            "name": "years",
            "in": "query",
            "required": true,
            "type": "date",
            "example": "2023"
          },
          {
            "name": "month",
            "in": "query",
            "required": true,
            "type": "date",
            "example": "06"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "ОК",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MonthTasksResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          },
          "404": {
            "description": "Bad request(invalid request body)"
          }
        }
      },
      "post": {
        "tags": ["Tasks"],
        "summary": "Add task to user",
        "parameters": [],
        "requestBody": {
          "description": "Task's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TaskCreationRequest"
              }
            }
          }
        },
        "security": [{ "Bearer": [] }],
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TaskCreationResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "response body": "Not authorized"
          },
          "404": {
            "description": "Bad request(invalid request body): start, end must be in HH-MM format, priority must be one of [low, medium, high],date must be in YYYY-MM-DD format, category must be one of [to-do, in-progress, done]"
          }
        }
      }
    },
    "/tasks/{id}": {
      "get": {
        "tags": ["Tasks"],
        "summary": "Get task by task's id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "example": "649d6172f796a41babf88dd8"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "ОК",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TaskByIdResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          },
          "404": {
            "description": "Task with {id} not found"
          }
        }
      },
      "delete": {
        "tags": ["Tasks"],
        "summary": "Delete task by task's id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "tasks's id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "ОК-Task deleted"
          },
          "401": {
            "description": "Not authorized"
          },
          "404": {
            "description": "Task with {id} not found"
          }
        }
      },
      "patch": {
        "tags": ["Tasks"],
        "summary": "Update task by task's id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "tasks's id",
            "example": "649d6a072e812167b5df7bd2"
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Task's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TaskUpdateRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "ОК",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TaskUpdateResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized"
          },
          "404": {
            "description": "Bad request(invalid request body): start, end must be in HH-MM format, priority must be one of [low, medium, high],date must be in YYYY-MM-DD format, category must be one of [to-do, in-progress, done]"
          }
        }
      }
    },
    "/tasks/statistics": {
      "post": {
        "tags": ["Tasks"],
        "summary": "Get user's task statistics",
        "parameters": [],
        "requestBody": {
          "description": "Statistics day object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/StatisticsCreationRequest"
              }
            }
          }
        },
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/StatisticsCreationResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "response body": "Not authorized"
          },
          "404": {
            "description": "Bad request(invalid request body)"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Bogdan"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "example": "bogdan@gmail.com",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "description": "User's token"
          },
          "refreshToken": {
            "type": "string",
            "description": "User's refreshToken"
          },
          "user": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "description": "User's id"
              },
              "name": {
                "type": "string",
                "description": "User's name"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email"
              },
              "avatarURL": {
                "type": "string",
                "description": "User's avatar path"
              }
            }
          }
        },

        "example": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYjEzOWRkMDlmY2E5YWFhNmRhNCIsImlhdCI6MTY4NzY5ODE5NSwiZXhwIjoxNjg3Njk4Mzc1fQ.P3ZWu3PzRpMyuT6ngche4ojbYizBvnOOnTSqniABkhQ",
          "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYjEzOWRkMDlmY2E5YWFhNmRhNCIsImlhdCI6MTY4NzY5ODE5NSwiZXhwIjoxNjg4MzAyOTk1fQ.Dycs8it1fF4WRFYiqV-0DDlZ3v_YRBTw6ThrOd5wx2A",
          "user": {
            "id": "64983b139dd09fca9aaa6da4",
            "name": "Bogdan",
            "email": "bogdan@gmail.com",
            "avatarURL": "http://www.gravatar.com/2a06849295a6965ddd313b186672c523.json"
          }
        }
      },
      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "example": "bogdan@gmail.com",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "LoginResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "description": "User's token"
          },
          "refreshToken": {
            "type": "string",
            "description": "User's refreshToken"
          },
          "user": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "description": "User's id"
              },
              "name": {
                "type": "string",
                "description": "User's name"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email"
              },
              "avatarURL": {
                "type": "string",
                "description": "User's avatar path"
              },
              "phone": {
                "type": "string",
                "description": "User's phone"
              },
              "birthday": {
                "type": "data",
                "description": "User's birthday"
              },
              "skype": {
                "type": "string",
                "description": "User's skype"
              }
            }
          }
        },

        "example": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYjEzOWRkMDlmY2E5YWFhNmRhNCIsImlhdCI6MTY4Nzc4NTk5MCwiZXhwIjoxNjg3Nzg2MTcwfQ.pDaxG-bCwh654H34GaqIDe6oByCLavaMCLN9o98X-5M",
          "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYjEzOWRkMDlmY2E5YWFhNmRhNCIsImlhdCI6MTY4Nzc4NTk5MCwiZXhwIjoxNjg4MzkwNzkwfQ.cUytD86J8B87cpas7O1mNvSPciSKAc7zcnPRd23p9zs",
          "user": {
            "id": "64983b139dd09fca9aaa6da4",
            "name": "Bogdan",
            "email": "bogdan@gmail.com",
            "avatarURL": "http://www.gravatar.com/c30d6c14569650b95a78e33e5013683e.json",
            "phone": null,
            "birthday": null,
            "skype": null
          }
        }
      },
      "CurrentUserResponse": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "User's id"
          },
          "name": {
            "type": "string",
            "description": "User's name"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "avatarURL": {
            "type": "string",
            "description": "User's avatar path"
          },
          "phone": {
            "type": "string",
            "description": "User's phone"
          },
          "birthday": {
            "type": "data",
            "description": "User's birthday"
          },
          "skype": {
            "type": "string",
            "description": "User's skype"
          }
        },

        "example": {
          "id": "64983b139dd09fca9aaa6da4",
          "name": "Bogdan",
          "email": "bogdan@gmail.com",
          "avatarURL": "http://www.gravatar.com/c30d6c14569650b95a78e33e5013683e.json",
          "phone": null,
          "birthday": null,
          "skype": null
        }
      },
      "UpdateUserRequest": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's new name",
            "example": "Bogdan"
          },
          "email": {
            "type": "string",
            "description": "User's new email",
            "example": "bogdan@gmail.com",
            "format": "email"
          },
          "avatarURL": {
            "type": "string",
            "description": "User's new avatar path",
            "format": "binary",
            "example": "Bogdan"
          },
          "phone": {
            "type": "string",
            "description": "User's new phone",
            "example": "00 (000) 000 00 00"
          },
          "birthday": {
            "type": "data",
            "description": "User's new birthday",
            "example": "07/03/1988"
          },
          "skype": {
            "type": "string",
            "description": "User's new skype",
            "example": "+1234567890"
          }
        }
      },
      "UpdateUserResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "description": "User's id"
          },
          "name": {
            "type": "string",
            "description": "User's name"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "avatarURL": {
            "type": "string",
            "description": "User's avatar path"
          },
          "phone": {
            "type": "string",
            "description": "User's phone"
          },
          "birthday": {
            "type": "data",
            "description": "User's birthday"
          },
          "skype": {
            "type": "string",
            "description": "User's skype"
          },
          "token": {
            "type": "string",
            "description": "User's token"
          },
          "refreshToken": {
            "type": "string",
            "description": "User's refreshToken"
          }
        },

        "example": {
          "_id": "64983b139dd09fca9aaa6da4",
          "name": "Bogdan",
          "email": "bogdan@gmail.com",
          "phone": "00 (000) 000 00 00",
          "birthday": "1988-07-03T00:00:00.000Z",
          "skype": "bogdanskype",
          "avatarURL": "http://res.cloudinary.com/drqfmqd2m/image/upload/v1688300646/avatar/joye1xqk08otdjshltlo.jpg",
          "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYjEzOWRkMDlmY2E5YWFhNmRhNCIsImlhdCI6MTY4ODMwMDUzNCwiZXhwIjoxNjg4MzA0MTM0fQ.Dd09QhieWWuLMcIQGOKkrTFIGpaziWU7Tig2JkAzzp0",
          "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYjEzOWRkMDlmY2E5YWFhNmRhNCIsImlhdCI6MTY4ODMwMDUzNCwiZXhwIjoxNjg4OTA1MzM0fQ.CbpkNjC5zQLVpAth0mhriN7qBY9bCJB2QEFJmxegxSM"
        }
      },
      "RefreshTokenRequest": {
        "type": "object",
        "required": ["refreshToken"],
        "properties": {
          "refreshToken": {
            "type": "string",
            "description": "User's refreshToken",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYjEzOWRkMDlmY2E5YWFhNmRhNCIsImlhdCI6MTY4ODA0NTc2MywiZXhwIjoxNjg4NjUwNTYzfQ.3rBPcxQO0-q8fgq7UN35HgX03lnapwprSBnd2gQj0Jo"
          }
        }
      },
      "RefreshTokenResponse": {
        "type": "object",
        "description": "New user's tokens",
        "properties": {
          "accessToken": {
            "type": "string",
            "description": "New accessToken"
          },
          "refreshToken": {
            "type": "number",
            "description": "New refreshToken"
          }
        },
        "example": {
          "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYjEzOWRkMDlmY2E5YWFhNmRhNCIsImlhdCI6MTY4ODA0NjU0NywiZXhwIjoxNjg4MDUwMTQ3fQ.Ag7JKkiqxE4FG-hksi_EUxcA_8BTyKeciySJGFL9XzQ",
          "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYjEzOWRkMDlmY2E5YWFhNmRhNCIsImlhdCI6MTY4ODA0NjU0NywiZXhwIjoxNjg4NjUxMzQ3fQ.bGUwhQQwkoZrZjqxrpBsdOklHfbTsPhd8Br00ogR0vw"
        }
      },
      "ReviewsResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Review id"
            },
            "rating": {
              "type": "number",
              "description": "Review rating"
            },
            "comment": {
              "type": "string",
              "description": "Review comment"
            },
            "owner": {
              "type": "object",
              "description": "Review owner",
              "properties": {
                "_id": {
                  "type": "string",
                  "description": "Owner id"
                },
                "name": {
                  "type": "string",
                  "description": "Owner name"
                },
                "avatarURL": {
                  "type": "string",
                  "description": "Owner avatarURL"
                }
              }
            },
            "createdAt": { "type": "string" },
            "updatedAt": { "type": "string" }
          }
        },
        "example": [
          {
            "_id": "649b43b13b98cd738d44bf7d",
            "rating": 5,
            "comment": "Very cool app, everything is clear and functional. A great program for time chronology.",
            "owner": {
              "_id": "649b43403b98cd738d44bf77",
              "name": "Vitalii",
              "avatarURL": "http://www.gravatar.com/43311ff72844c2febf41f3a2e3fe91b7.json"
            },
            "createdAt": "2023-06-27T20:16:49.198Z",
            "updatedAt": "2023-06-27T20:16:49.198Z"
          },
          {
            "_id": "649c02e4d5ae7f2605a11aac",
            "rating": 3,
            "comment": "A pleasant find for me. It's exactly what I was looking for. The main advantage is the visual visualization in the form of boards and cards. I recommend it!",
            "owner": {
              "_id": "64983b139dd09fca9aaa6da4",
              "name": "Bogdan",
              "avatarURL": "http://www.gravatar.com/c30d6c14569650b95a78e33e5013683e.json"
            },
            "createdAt": "2023-06-28T09:52:36.971Z",
            "updatedAt": "2023-06-28T09:52:36.971Z"
          }
        ]
      },
      "ReviewCreationRequest": {
        "type": "object",
        "required": ["rating", "comment"],
        "properties": {
          "rating": {
            "type": "number",
            "description": "Review rating",
            "example": "3"
          },
          "comment": {
            "type": "string",
            "description": "Review comment",
            "example": "A pleasant find for me. It's exactly what I was looking for. The main advantage is the visual visualization in the form of boards and cards. I recommend it!"
          }
        }
      },
      "ReviewCreationResponse": {
        "type": "object",
        "description": "User's created review",
        "properties": {
          "_id": {
            "type": "string",
            "description": "Review id"
          },
          "rating": {
            "type": "number",
            "description": "Review rating"
          },
          "comment": {
            "type": "string",
            "description": "Review comment"
          },
          "owner": {
            "type": "string",
            "description": "Owner id"
          },
          "createdAt": { "type": "string" },
          "updatedAt": { "type": "string" }
        },
        "example": {
          "rating": 3,
          "comment": "A pleasant find for me. It's exactly what I was looking for. The main advantage is the visual visualization in the form of boards and cards. I recommend it!",
          "owner": "64983b139dd09fca9aaa6da4",
          "_id": "649c214a1f128a4c54da4b52",
          "createdAt": "2023-06-28T12:02:18.465Z",
          "updatedAt": "2023-06-28T12:02:18.465Z"
        }
      },
      "ReviewByUserIdResponse": {
        "type": "object",
        "description": "Review got by user's id ",
        "properties": {
          "_id": {
            "type": "string",
            "description": "Review id"
          },
          "rating": {
            "type": "number",
            "description": "Review rating"
          },
          "comment": {
            "type": "string",
            "description": "Review comment"
          },
          "owner": {
            "type": "object",
            "description": "Review owner",
            "properties": {
              "_id": {
                "type": "string",
                "description": "Owner id"
              },
              "name": {
                "type": "string",
                "description": "Owner name"
              },
              "avatarURL": {
                "type": "string",
                "description": "Owner avatarURL"
              }
            }
          },
          "createdAt": { "type": "string" },
          "updatedAt": { "type": "string" }
        },
        "example": {
          "_id": "649c02e4d5ae7f2605a11aac",
          "rating": 3,
          "comment": "A pleasant find for me. It's exactly what I was looking for. The main advantage is the visual visualization in the form of boards and cards. I recommend it!",
          "owner": {
            "_id": "64983b139dd09fca9aaa6da4",
            "name": "Bogdan",
            "avatarURL": "http://www.gravatar.com/c30d6c14569650b95a78e33e5013683e.json"
          },
          "createdAt": "2023-06-28T09:52:36.971Z",
          "updatedAt": "2023-06-28T09:52:36.971Z"
        }
      },
      "ReviewUpdateRequest": {
        "type": "object",
        "required": ["rating", "comment"],
        "properties": {
          "rating": {
            "type": "number",
            "description": "Review rating",
            "example": "4"
          },
          "comment": {
            "type": "string",
            "description": "Review comment",
            "example": "The main advantage is the visual visualization. I recommend it!"
          }
        }
      },
      "ReviewUpdateResponse": {
        "type": "object",
        "description": "Review got by user's id ",
        "properties": {
          "_id": {
            "type": "string",
            "description": "Review id"
          },
          "rating": {
            "type": "number",
            "description": "Review rating"
          },
          "comment": {
            "type": "string",
            "description": "Review comment"
          },
          "owner": {
            "type": "object",
            "description": "Review owner",
            "properties": {
              "_id": {
                "type": "string",
                "description": "Owner id"
              },
              "name": {
                "type": "string",
                "description": "Owner name"
              },
              "avatarURL": {
                "type": "string",
                "description": "Owner avatarURL"
              }
            }
          },
          "createdAt": { "type": "string" },
          "updatedAt": { "type": "string" }
        },
        "example": {
          "_id": "649c02e4d5ae7f2605a11aac",
          "rating": 4,
          "comment": "The main advantage is the visual visualization. I recommend it!",
          "owner": {
            "_id": "64983b139dd09fca9aaa6da4",
            "name": "Bogdan",
            "avatarURL": "http://www.gravatar.com/c30d6c14569650b95a78e33e5013683e.json"
          },
          "createdAt": "2023-06-28T09:52:36.971Z",
          "updatedAt": "2023-06-30T13:18:00.453Z"
        }
      },
      "MonthTasksResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "User's task id"
            },
            "title": {
              "type": "string",
              "description": "User's task title"
            },
            "start": {
              "type": "string",
              "description": "User's task start time must be in HH-MM format"
            },
            "end": {
              "type": "string",
              "description": "User's task end time must be in HH-MM format"
            },
            "priority": {
              "type": "string",
              "description": "User's task priority must be one of [low, medium, high]"
            },
            "date": {
              "type": "Date",
              "description": "User's task date must be in YYYY-MM-DD format"
            },
            "category": {
              "type": "string",
              "description": "User's task priority must be one of [to-do, in-progress, done]"
            },
            "owner": {
              "type": "string",
              "description": "User's task owner id"
            },

            "createdAt": { "type": "string" },
            "updatedAt": { "type": "string" }
          }
        },
        "example": {
          "tasks": [
            {
              "_id": "649c7eee04b4eed7994ac415",
              "title": "To learn react-native",
              "start": "08-00",
              "end": "12-00",
              "priority": "low",
              "date": "2023-06-30T00:00:00.000Z",
              "category": "to-do",
              "owner": "64983b139dd09fca9aaa6da4",
              "createdAt": "2023-06-28T18:41:50.296Z",
              "updatedAt": "2023-06-28T18:41:50.296Z"
            },
            {
              "_id": "649d6a072e812167b5df7bd2",
              "title": "To learn react",
              "start": "08-00",
              "end": "12-00",
              "priority": "high",
              "date": "2023-06-30T00:00:00.000Z",
              "category": "to-do",
              "owner": "64983b139dd09fca9aaa6da4",
              "createdAt": "2023-06-29T11:24:55.187Z",
              "updatedAt": "2023-06-30T12:08:09.578Z"
            }
          ]
        }
      },
      "TaskCreationRequest": {
        "type": "object",
        "required": ["title", "start", "end", "priority", "date", "category"],
        "properties": {
          "title": {
            "type": "string",
            "description": "User's task title",
            "example": "To learn react-native"
          },
          "start": {
            "type": "string",
            "description": "User's task start time must be in HH-MM format",
            "example": "08-00"
          },
          "end": {
            "type": "string",
            "description": "User's task end time must be in HH-MM format",
            "example": "12-00"
          },
          "priority": {
            "type": "string",
            "description": "User's task priority must be one of [low, medium, high]",
            "example": "high"
          },
          "date": {
            "type": "date",
            "description": "User's task date must be in YYYY-MM-DD format",
            "example": "2023-06-30"
          },
          "category": {
            "type": "string",
            "description": "User's task priority must be one of [to-do, in-progress, done]",
            "example": "to-do"
          }
        }
      },
      "TaskCreationResponse": {
        "type": "object",
        "description": "User's task",
        "properties": {
          "title": {
            "type": "string",
            "description": "User's task title"
          },
          "start": {
            "type": "string",
            "description": "User's task start time must be in HH-MM format"
          },
          "end": {
            "type": "string",
            "description": "User's task end time must be in HH-MM format"
          },
          "priority": {
            "type": "string",
            "description": "User's task priority must be one of [low, medium, high]"
          },
          "date": {
            "type": "Date",
            "description": "User's task date must be in YYYY-MM-DD format"
          },
          "category": {
            "type": "string",
            "description": "User's task priority must be one of [to-do, in-progress, done]"
          },
          "owner": {
            "type": "string",
            "description": "User's task owner id"
          },
          "_id": {
            "type": "string",
            "description": "User's task id"
          },
          "createdAt": { "type": "string" },
          "updatedAt": { "type": "string" }
        },
        "example": {
          "title": "To learn react-native",
          "start": "08-00",
          "end": "12-00",
          "priority": "high",
          "date": "2023-06-30T00:00:00.000Z",
          "category": "to-do",
          "owner": "64983b139dd09fca9aaa6da4",
          "_id": "649c7eee04b4eed7994ac415",
          "createdAt": "2023-06-28T18:41:50.296Z",
          "updatedAt": "2023-06-28T18:41:50.296Z"
        }
      },
      "TaskByIdResponse": {
        "type": "object",
        "description": "User's task",
        "properties": {
          "_id": {
            "type": "string",
            "description": "User's task by task's id"
          },
          "title": {
            "type": "string",
            "description": "User's task title"
          },
          "start": {
            "type": "string",
            "description": "User's task start time must be in HH-MM format"
          },
          "end": {
            "type": "string",
            "description": "User's task end time must be in HH-MM format"
          },
          "priority": {
            "type": "string",
            "description": "User's task priority must be one of [low, medium, high]"
          },
          "date": {
            "type": "Date",
            "description": "User's task date must be in YYYY-MM-DD format"
          },
          "category": {
            "type": "string",
            "description": "User's task priority must be one of [to-do, in-progress, done]"
          },
          "owner": {
            "type": "string",
            "description": "User's task owner id"
          },
          "createdAt": { "type": "string" },
          "updatedAt": { "type": "string" }
        },
        "example": {
          "_id": "649d6172f796a41babf88dd8",
          "title": "To learn Angular",
          "start": "08-00",
          "end": "12-00",
          "priority": "high",
          "date": "2023-07-04T00:00:00.000Z",
          "category": "to-do",
          "owner": "64983b139dd09fca9aaa6da4",
          "createdAt": "2023-06-29T10:48:18.239Z",
          "updatedAt": "2023-06-29T10:48:18.239Z"
        }
      },
      "TaskUpdateRequest": {
        "type": "object",
        "required": ["title", "start", "end", "priority", "date", "category"],
        "properties": {
          "title": {
            "type": "string",
            "description": "User's task title",
            "example": "To learn react-native"
          },
          "start": {
            "type": "string",
            "description": "User's task start time must be in HH-MM format",
            "example": "08-00"
          },
          "end": {
            "type": "string",
            "description": "User's task end time must be in HH-MM format",
            "example": "12-00"
          },
          "priority": {
            "type": "string",
            "description": "User's task priority must be one of [low, medium, high]",
            "example": "high"
          },
          "date": {
            "type": "date",
            "description": "User's task date must be in YYYY-MM-DD format",
            "example": "2023-06-30"
          },
          "category": {
            "type": "string",
            "description": "User's task priority must be one of [to-do, in-progress, done]",
            "example": "to-do"
          }
        }
      },
      "TaskUpdateResponse": {
        "type": "object",
        "description": "User's updated task",
        "properties": {
          "_id": {
            "type": "string",
            "description": "User's task by task's id"
          },
          "title": {
            "type": "string",
            "description": "User's task title"
          },
          "start": {
            "type": "string",
            "description": "User's task start time must be in HH-MM format"
          },
          "end": {
            "type": "string",
            "description": "User's task end time must be in HH-MM format"
          },
          "priority": {
            "type": "string",
            "description": "User's task priority must be one of [low, medium, high]"
          },
          "date": {
            "type": "Date",
            "description": "User's task date must be in YYYY-MM-DD format"
          },
          "category": {
            "type": "string",
            "description": "User's task priority must be one of [to-do, in-progress, done]"
          },
          "owner": {
            "type": "string",
            "description": "User's task owner id"
          },
          "createdAt": { "type": "string" },
          "updatedAt": { "type": "string" }
        },
        "example": {
          "_id": "649d6a072e812167b5df7bd2",
          "title": "To learn react-native",
          "start": "08-00",
          "end": "12-00",
          "priority": "high",
          "date": "2023-06-30T00:00:00.000Z",
          "category": "to-do",
          "owner": "64983b139dd09fca9aaa6da4",
          "createdAt": "2023-06-29T11:24:55.187Z",
          "updatedAt": "2023-06-30T11:27:02.276Z"
        }
      },
      "StatisticsCreationRequest": {
        "type": "object",
        "required": ["date"],
        "properties": {
          "date": {
            "type": "date",
            "description": "User's statistics date must be in YYYY-MM-DD format",
            "example": "2023-07-05"
          }
        }
      },
      "StatisticsCreationResponse": {
        "type": "object",
        "description": "User's statistics",
        "properties": {
          "todoByDayPercentage": {
            "type": "string",
            "description": "User's task day to-do statistics"
          },
          "inprogressByDayPercentage": {
            "type": "string",
            "description": "User's task day in-progress statistics"
          },
          "doneByDayPercentage": {
            "type": "string",
            "description": "User's task day done statistics"
          },
          "todoByMonthPercentage": {
            "type": "string",
            "description": "User's task month to-do statistics"
          },
          "inprogressByMonthPercentage": {
            "type": "string",
            "description": "User's task month in-progress statistics"
          },
          "doneByMonthPercentage": {
            "type": "string",
            "description": "User's task month done statistics"
          }
        },
        "example": {
          "todoByDayPercentage": 0,
          "inprogressByDayPercentage": 100,
          "doneByDayPercentage": 0,
          "todoByMonthPercentage": 46,
          "inprogressByMonthPercentage": 15,
          "doneByMonthPercentage": 38
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "in": "header",
        "name": "Authorization",
        "description": "Bearer token to access these api endpoints"
      }
    }
  }
}
